name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install gdown
      run: pip3 install gdown
    - name: Docker Login
      run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
    - name: Build the Docker image
      run: docker build -t demo_repo:latest -f ./BuildDemo .
    - name: check docker images
      run: docker images
    - name: check containers
      run: docker ps -a
    - name: Docker Push
      run: docker push ${{secrets.DOCKER_USER}}/demo_repo:latest
      
