name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PROJECT_ID: polished-cocoa-365814
  GAR_LOCATION: us-central1

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Checker
      run: ls -lah
      
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
    
    - name: Docker Auth
      id: docker-auth
      uses: 'docker/login-action@v2.1.0'
      with:
        username: _json_key
        password: ${{ secrets.GOOGLE_CREDENTIALS }}
        registry: ${{ env.GAR_LOCATION }}-docker.pkg.dev
    
    - name: Get Docker Image
      run: docker pull codeadeel/stream_classification:video_client_browser
    
    - name: Rename Image
      run: docker tag codeadeel/stream_classification:video_client_browser ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/streamclassification/stream_classification:video_client_browser
    
    - name: Check available images
      run: docker images
    
    - name: Push image
      run: docker push ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/streamclassification/stream_classification:video_client_browser


    
