name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: main Branch Checkout
      uses: actions/checkout@v4

    - name: ZeroTier Login
      uses: zerotier/github-action@v1
      with:
        network_id: ${{ secrets.FNIRSZEROTIERNETWORK }}
        auth_token: ${{ secrets.FNIRSZEROTIERTOKEN }}

    - name: ping host
      shell: bash
      run: |
        count=10
        while ! ping -c 1 ${{ secrets.FNIRSGCPHOST }} ; do
          echo "waiting..." ;
          sleep 1 ;
          let count=count-1
        done
        echo "ping success"
    
    - name: Generating SSH Key
      run: echo "${{ secrets.FNIRSGCPKEY }}" > ./tempKey
    
    - name: Setting Permission to SSH Key
      run: chmod 600 ./tempKey
    
    - name: Checking pwd
      run: pwd

    - name: Checking ls
      run:  ls -lah
      
    - name: Testing SSH
      shell: bash
      run: |
        ssh -o "StrictHostKeyChecking no" -i ./tempKey ${{ secrets.FNIRSGCPUSER }}@${{ secrets.FNIRSGCPHOST }} sudo pwd
        ssh -o "StrictHostKeyChecking no" -i ./tempKey ${{ secrets.FNIRSGCPUSER }}@${{ secrets.FNIRSGCPHOST }} sudo ls -lah
        
