name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: main Branch Checkout
      uses: actions/checkout@v4

    - name: check npm version
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    
    - name: check node version
      run: node -v
        
